cc_library(
  name="prussdrv",
  visibility=["//visibility:public"],
  srcs = [
    "interface/prussdrv.c",
  ],
  hdrs = [
    "interface/__prussdrv.h",
    "include/prussdrv.h",
    "include/pruss_intc_mapping.h",
  ],
)
