#load(":toolchain.bzl", "BEAGLEBONE_TOOLCHAIN", "beaglebone_toolchain_info")

#beaglebone_toolchain_info(
#    name = "beaglebone_toolchain_info/armv7-linux-gnu",
#    cflags = ["--target-os=linux", "--target-arch=armv7"],
#)

#demo_toolchain_info(
#    name = "demo_toolchain_info/arm-linux-gnu",
#    cflags = ["--target-os=linux", "--target-arch=arm"],
#)
